var modules =
[
    [ "FreeRTOS Configurations.", "d7/d7d/group__i2__FreeRTOS__config.html", "d7/d7d/group__i2__FreeRTOS__config" ],
    [ "FreeRTOS co-routine definitions.", "da/db9/group__i2__FreeRTOS__Co__Routines.html", "da/db9/group__i2__FreeRTOS__Co__Routines" ],
    [ "FreeRTOS software timer definitions.", "dd/de6/group__i2__FreeRTOS__Timers.html", "dd/de6/group__i2__FreeRTOS__Timers" ],
    [ "FreeRTOS additional APIs.", "dd/d6f/group__i2__FreeRTOS__Tasks.html", "dd/d6f/group__i2__FreeRTOS__Tasks" ],
    [ "FreeRTOS Cortex-M specific definitions.", "db/daa/group__i2__FreeRTOS__CortexM.html", "db/daa/group__i2__FreeRTOS__CortexM" ],
    [ "FreeRTOS interrupt Handler.", "d2/d0b/group__i2__FreeRTOS__IRQn.html", "d2/d0b/group__i2__FreeRTOS__IRQn" ],
    [ "iota2 Firmware version.", "db/dc4/group__I2__HUB__VERSION.html", "db/dc4/group__I2__HUB__VERSION" ],
    [ "HAL drivers enabling.", "dd/df7/group__HAL__ENABLED__MODULES.html", "dd/df7/group__HAL__ENABLED__MODULES" ],
    [ "HAL system configuration section.", "d1/dfb/group__HAL__SYSTEM__CONFIG.html", "d1/dfb/group__HAL__SYSTEM__CONFIG" ],
    [ "Ethernet peripheral configuration.", "de/d8b/group__HAL__ETH__CONFIG.html", "de/d8b/group__HAL__ETH__CONFIG" ],
    [ "Assert definition.", "d6/df8/group__I2__ASSERT.html", "d6/df8/group__I2__ASSERT" ],
    [ "iota2 unified Error Codes.", "db/d8c/group__I2__ERROR.html", "db/d8c/group__I2__ERROR" ],
    [ "FIFO context.", "dd/dde/group__i2__fifo__t.html", "dd/dde/group__i2__fifo__t" ],
    [ "Font indexing for user defined characters.", "d5/df3/group__i2__font5x7__custom__char.html", "d5/df3/group__i2__font5x7__custom__char" ],
    [ "LED used in system.", "d3/dd9/group__i2__led__t.html", "d3/dd9/group__i2__led__t" ],
    [ "SSD1306 display parameter specification.", "dd/d95/group__SSD1306__DISPLAY__SPEC.html", "dd/d95/group__SSD1306__DISPLAY__SPEC" ],
    [ "Display color specifications.", "d2/d25/group__SSD1306__COLOR__SPEC.html", "d2/d25/group__SSD1306__COLOR__SPEC" ],
    [ "SSD1306 display multi-layer support.", "db/d6a/group__SSD1306__MULTI__LAYER__SPEC.html", "db/d6a/group__SSD1306__MULTI__LAYER__SPEC" ],
    [ "SSD1306 text display specifications.", "d8/d4f/group__SSD1306__TEXT__SPEC.html", "d8/d4f/group__SSD1306__TEXT__SPEC" ],
    [ "SSD1306 command set.", "d2/de2/group__SSD1306__CMD__SPEC.html", "d2/de2/group__SSD1306__CMD__SPEC" ],
    [ "SSD1306 configurations.", "d6/dd6/group__SSD1306__CONFIG__SPEC.html", "d6/dd6/group__SSD1306__CONFIG__SPEC" ],
    [ "SSD1306 scrolling options.", "df/db6/group__SSD1306__SCROLL__SPEC.html", "df/db6/group__SSD1306__SCROLL__SPEC" ],
    [ "SSD1306 display point specification.", "d0/d50/group__SSD1306__POINT__SPEC.html", "d0/d50/group__SSD1306__POINT__SPEC" ],
    [ "SSD1306 polygon specification.", "d6/dc5/group__SSD1306__POLYGON__SPEC.html", "d6/dc5/group__SSD1306__POLYGON__SPEC" ],
    [ "iota2 standard ASCII 5x7 font.", "d0/d1e/group__i2__font5x7.html", "d0/d1e/group__i2__font5x7" ],
    [ "LED pin specification.", "d9/d43/group__I2__LED.html", "d9/d43/group__I2__LED" ],
    [ "SSD1306 Hardware Pins Definition.", "d5/d1e/group__SSD1306__HW__SPEC.html", "d5/d1e/group__SSD1306__HW__SPEC" ],
    [ "SSD1306 SPI instance.", "d6/d79/group__SSD1306__SPI__SPEC.html", "d6/d79/group__SSD1306__SPI__SPEC" ],
    [ "SSD1306 GPIO pins definition.", "d4/dce/group__SSD1306__PIN__SPEC.html", "d4/dce/group__SSD1306__PIN__SPEC" ],
    [ "SSD1306  display buffers.", "db/d36/group__SSD1306__LAYER__BUFFER__SPEC.html", "db/d36/group__SSD1306__LAYER__BUFFER__SPEC" ],
    [ "HAL core operational mode.", "d1/d7f/group__i2__hal__mode__t.html", "d1/d7f/group__i2__hal__mode__t" ],
    [ "iota2 generic callback Handlers.", "d4/d90/group__i2__handler__t.html", "d4/d90/group__i2__handler__t" ],
    [ "HAL core driver transfer status.", "d7/de1/group__I2__TRANSFER__STATE.html", "d7/de1/group__I2__TRANSFER__STATE" ],
    [ "iota2 Enabling options.", "de/d69/group__I2__DISABLE__ENABLE.html", "de/d69/group__I2__DISABLE__ENABLE" ],
    [ "iota2 pin control settings.", "dd/d6b/group__I2__LOW__HIGH.html", "dd/d6b/group__I2__LOW__HIGH" ],
    [ "GPIO interface instance.", "d0/dd7/group__i2__gpio__inst__t.html", "d0/dd7/group__i2__gpio__inst__t" ],
    [ "RTC Alarm instances.", "df/d78/group__rtc__alarm__t.html", "df/d78/group__rtc__alarm__t" ],
    [ "RTC Alarm type.", "d6/d30/group__rtc__alarm__type__t.html", "d6/d30/group__rtc__alarm__type__t" ],
    [ "SPI Operation Modes.", "db/d36/group__i2__spi__mode__t.html", "db/d36/group__i2__spi__mode__t" ],
    [ "SPI data width.", "d5/dbb/group__i2__spi__data__width__t.html", "d5/dbb/group__i2__spi__data__width__t" ],
    [ "SPI clock speed.", "d4/d6b/group__i2__spi__clock__speed__t.html", "d4/d6b/group__i2__spi__clock__speed__t" ],
    [ "SPI First bit to send / receive.", "d6/d81/group__i2__spi__first__bit__t.html", "d6/d81/group__i2__spi__first__bit__t" ],
    [ "SPI peripheral instance.", "d2/d95/group__i2__spi__inst__t.html", "d2/d95/group__i2__spi__inst__t" ],
    [ "UART peripheral instance.", "d2/d1f/group__i2__uart__inst__t.html", "d2/d1f/group__i2__uart__inst__t" ],
    [ "iota2 and HAL errors mapping context.", "d6/dfe/group__i2__error__t.html", "d6/dfe/group__i2__error__t" ],
    [ "iota2 and HAL errors mapping table.", "da/d0c/group__HAL__ERROR__MAPPING.html", "da/d0c/group__HAL__ERROR__MAPPING" ],
    [ "GPIO port context.", "d9/dd5/group__i2__gpio__ctx__t.html", "d9/dd5/group__i2__gpio__ctx__t" ],
    [ "GPIO ports list.", "df/dd1/group__GPIO__PORTS.html", "df/dd1/group__GPIO__PORTS" ],
    [ "GPIO pins list.", "d7/dfd/group__GPIO__PINS.html", "d7/dfd/group__GPIO__PINS" ],
    [ "RTC peripheral context.", "db/de5/group__rtc__ctx.html", "db/de5/group__rtc__ctx" ],
    [ "SPI configurations.", "d5/da8/group__I2__SPI__CONFIG.html", null ],
    [ "SPI peripherals enabling.", "db/df3/group__I2__ENABLE__SPI__CONTEXT.html", "db/df3/group__I2__ENABLE__SPI__CONTEXT" ],
    [ "SPI1 configurations.", "d8/d08/group__I2__SPI1__CONFIG.html", "d8/d08/group__I2__SPI1__CONFIG" ],
    [ "SPI2 configurations.", "d1/d03/group__I2__SPI2__CONFIG.html", "d1/d03/group__I2__SPI2__CONFIG" ],
    [ "SPI3 configurations.", "d7/d7f/group__I2__SPI3__CONFIG.html", "d7/d7f/group__I2__SPI3__CONFIG" ],
    [ "SPI peripheral context.", "dc/d80/group__i2__spi__ctx__t.html", "dc/d80/group__i2__spi__ctx__t" ],
    [ "UART configurations.", "da/d91/group__I2__UART__CONFIG.html", null ],
    [ "UART peripheral enabling.", "d8/dd5/group__I2__ENABLE__UART__CONTEXT.html", "d8/dd5/group__I2__ENABLE__UART__CONTEXT" ],
    [ "UART1 configurations.", "d0/d3e/group__I2__UART1__CONFIG.html", "d0/d3e/group__I2__UART1__CONFIG" ],
    [ "UART2 configurations.", "d6/db0/group__I2__UART2__CONFIG.html", "d6/db0/group__I2__UART2__CONFIG" ],
    [ "UART3 configurations.", "de/d1c/group__I2__UART3__CONFIG.html", "de/d1c/group__I2__UART3__CONFIG" ],
    [ "UART4 configurations.", "d3/d40/group__I2__UART4__CONFIG.html", "d3/d40/group__I2__UART4__CONFIG" ],
    [ "UART5 configurations.", "d1/d27/group__I2__UART5__CONFIG.html", "d1/d27/group__I2__UART5__CONFIG" ],
    [ "UART6 configurations.", "d9/d94/group__I2__UART6__CONFIG.html", "d9/d94/group__I2__UART6__CONFIG" ],
    [ "UART peripheral context.", "d6/d8f/group__i2__uart__ctx__t.html", "d6/d8f/group__i2__uart__ctx__t" ],
    [ "STM32F4xx_StdPeriph_Examples", "de/d9f/group__STM32F4xx__StdPeriph__Examples.html", "de/d9f/group__STM32F4xx__StdPeriph__Examples" ],
    [ "CMSIS", "dd/d3b/group__CMSIS.html", "dd/d3b/group__CMSIS" ]
];